site_name: Some name
site_url: https://hsi.eng.waikato.ac.nz/
site_description: Website for the Hyperspectral Imaging Group at the University of Waikato.
repo_url: https://github.com/wairas/hsi-website
edit_uri: edit/main/docs/
theme:
    name: material
    logo: logo.png
    favicon: favicon.ico
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"
    - attr_list
    - sane_lists
plugins:
    - search
    # https://github.com/soulless-viewer/mkdocs-video
    - mkdocs-video
    # https://github.com/timvink/mkdocs-table-reader-plugin
    - table-reader
nav:
  - 'Home': index.md
  - 'Menu':
    - 'HSI':
      - 'Home': homehsi.md
      - 'HAPPy':
        - 'Introduction': happy/index.md
        - 'WSL2': happy/wsl2.md
        - 'Installation': happy/installation.md
        - 'Docker': happy/docker.md
        - 'ADAMS': happy/adams.md
        - 'happy-tools':
          - 'Overview': happy/happy_tools/index.md
          - 'Core command-line tools':
            - 'happy-ann2happy': happy/happy_tools/happy-ann2happy.md
            - 'happy-generate-image-regions-objects': happy/happy_tools/happy-generate-image-regions-objects.md
            - 'happy-hdr-info': happy/happy_tools/happy-hdr-info.md
            - 'happy-hsi2rbg': happy/happy_tools/happy-hsi2rbg.md
            - 'happy-mat-info': happy/happy_tools/happy-mat-info.md
            - 'happy-opex-labels': happy/happy_tools/happy-opex-labels.md
            - 'happy-plot-preproc': happy/happy_tools/happy-plot-preproc.md
            - 'happy-process-data': happy/happy_tools/happy-process-data.md
            - 'happy-raw-check': happy/happy_tools/happy-raw-check.md
            - 'happy-scikit-regression-build': happy/happy_tools/happy-scikit-regression-build.md
            - 'happy-scikit-segmentation-build': happy/happy_tools/happy-scikit-segmentation-build.md
            - 'happy-scikit-unsupervised-build': happy/happy_tools/happy-scikit-unsupervised-build.md
            - 'happy-splitter': happy/happy_tools/happy-splitter.md
            - 'happy-sub-images': happy/happy_tools/happy-sub-images.md
        - 'happy-tools-tkinter':
          - 'Overview': happy/happy_tools_tkinter/index.md
          - 'happy-data-viewer': happy/happy_tools_tkinter/happy-data-viewer.md
          - 'happy-envi-viewer': happy/happy_tools_tkinter/happy-envi-viewer.md
          - 'happy-raw-checker': happy/happy_tools_tkinter/happy-raw-checker.md
        - 'happy-tools-keras':
          - 'Overview': happy/happy_tools_keras/index.md
          - 'Command-line tools':
            - 'happy-keras-pixel-regression-build': happy/happy_tools_keras/happy-keras-pixel-regression-build.md
            - 'happy-keras-segmentation-build': happy/happy_tools_keras/happy-keras-segmentation-build.md
            - 'happy-keras-unsupervised-build': happy/happy_tools_keras/happy-keras-unsupervised-build.md
        - 'SAM': happy/sam.md
        - 'SAM-HQ': happy/sam-hq.md
      - 'Hardware': hardware.md
      - 'Publications': publications.md
      - 'Team': team.md
    - 'WAILight':
      - 'Home': wailight/homewailight.md
      - 'Publications': wailight/pubwailight.md
    - 'RuralAI':
      - 'Home': ruralai/homeruralai.md
      - 'Publications': ruralai/pubruralai.md

